const pseudocode = {
  bubble: [
    'for i from 0 to n-1',
    '  for j from 0 to n-i-2',
    '    if arr[j] > arr[j+1]',
    '      swap(arr[j], arr[j+1])',
    '  mark arr[n-i-1] as sorted',
    'done',
  ],
  selection: [
    'for i from 0 to n-1',
    '  minIdx = i',
    '  for j from i+1 to n',
    '    if arr[j] < arr[minIdx]',
    '      minIdx = j',
    '  swap(arr[i], arr[minIdx])',
    '  mark arr[i] as sorted',
    'done',
  ],
  insertion: [
    'mark arr[0] as sorted',
    'for i from 1 to n',
    '  key = arr[i]',
    '  j = i - 1',
    '  while j >= 0 and arr[j] > key',
    '    arr[j+1] = arr[j]',
    '    j = j - 1',
    '  arr[j+1] = key',
    'done',
  ],
  merge: [
    'mergeSort(arr, left, right)',
    '  if left >= right: return',
    '  mid = (left + right) / 2',
    '  mergeSort(arr, left, mid)',
    '  mergeSort(arr, mid+1, right)',
    '  merge(arr, left, mid, right)',
    'merge: compare and place elements',
    'done',
  ],
  quick: [
    'quickSort(arr, low, high)',
    '  if low >= high: return',
    '  pivot = arr[high]',
    '  i = low - 1',
    '  for j from low to high-1',
    '    if arr[j] <= pivot',
    '      i++, swap(arr[i], arr[j])',
    '  swap(arr[i+1], arr[high])',
    '  recurse left and right partitions',
  ],
}

export default pseudocode